title: Pasha's GenAI Blog
tagline: My journey into Generative AI
description: Learning and explaining GenAI, LLMs, prompts, RAG, and more.
url: "https://shaikjanipasha.github.io"
baseurl: "/janipasha.github.io"
author:
  name: Pasha
  bio: Lead Software Engineer
